Repository openshift/cluster-autoscaler-operator, pull requests merged in 2018-10, with the labels that each got.

#5 remove copyright notice
  Makefile
Labels: lgtm, size/S

#2 Update ClusterAutoscaler CRD
  examples/clusterautoscaler.yaml
  pkg/apis/autoscaling/v1alpha1/types.go
  pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/handler.go
  tmp/codegen/update-generated.sh
Labels: size/L

#3 Add MachineAutoscaler resource
  cmd/cluster-autoscaler-operator/main.go
  examples/clusterautoscaler.yaml
  examples/machineautoscaler.yaml
  install/0000_50_cluster-autoscaler-operator_02_machineautoscaler.crd.yaml
  install/0000_50_cluster-autoscaler-operator_03_rbac.yaml
  pkg/apis/autoscaling/v1alpha1/register.go
  pkg/apis/autoscaling/v1alpha1/types.go
  pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/handler.go
Labels: lgtm, size/L

#6 fix fmt script invocation and remove k8s copyright notice
  Dockerfile
  Makefile
Labels: approved, lgtm, size/S
