Repository openshift/cluster-autoscaler-operator, pull requests merged in 2019-01, with the labels that each got.

#26 Add MachineDeployment as a supported target
  pkg/controller/machineautoscaler/machineautoscaler_controller.go
Labels: approved, lgtm, size/XS

#25 Mark targets as owned by MachineAutoscaler resources
  pkg/controller/machineautoscaler/machineautoscaler_controller.go
  pkg/controller/machineautoscaler/machinetarget.go
  pkg/controller/machineautoscaler/machinetarget_test.go
Labels: approved, lgtm, size/L

#28 Printer columns for machine autoscaler
  install/0000_50_cluster-autoscaler-operator_02_machineautoscaler.crd.yaml
Labels: approved, lgtm, size/S

#30 Use correct cluster-autoscaler image reference
  install/0000_50_cluster-autoscaler-operator_04_deployment.yaml
  install/image-references
Labels: approved, lgtm, size/XS

#29 Only run the autoscaler pod on Linux nodes
  pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
Labels: approved, lgtm, size/XS

#31 Finalize previous MachineAutoscaler targets on update
  Makefile
  install/0000_50_cluster-autoscaler-operator_02_machineautoscaler.crd.yaml
  pkg/apis/autoscaling/v1alpha1/machineautoscaler_types.go
  pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/machineautoscaler/machineautoscaler_controller.go
  pkg/controller/machineautoscaler/machinetarget.go
  pkg/controller/machineautoscaler/machinetarget_test.go
  pkg/operator/operator.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, lgtm, size/L

#32 Properly validate MachineAutoscaler target references
  pkg/controller/machineautoscaler/machineautoscaler_controller.go
  pkg/controller/machineautoscaler/machineautoscaler_controller_test.go
Labels: approved, lgtm, size/M

#33 Ignore not-found errors when finalizing resources
  pkg/controller/machineautoscaler/machineautoscaler_controller.go
Labels: approved, lgtm, size/M
