Repository openshift/cluster-autoscaler-operator, pull requests merged in 2019-06, with the labels that each got.

#103 Switch builds to use Go 1.12
  Dockerfile
  Dockerfile.rhel7
  Makefile
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
Labels: approved, lgtm, size/S

#104 Monitoring integration
  cmd/manager/main.go
  install/00_namespace.yaml
  install/03_rbac.yaml
  install/04_service.yaml
  install/06_deployment.yaml
  install/09_servicemonitor.yaml
  pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
  pkg/controller/machineautoscaler/machineautoscaler_controller.go
  pkg/operator/config.go
  pkg/operator/config_test.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/L

#102 Enable autoscaler --balance-similar-node-groups option
  README.md
  examples/clusterautoscaler.yaml
  install/01_clusterautoscaler.crd.yaml
  pkg/apis/autoscaling/v1/clusterautoscaler_types.go
  pkg/apis/autoscaling/v1/zz_generated.deepcopy.go
  pkg/apis/autoscaling/v1/zz_generated.openapi.go
  pkg/controller/clusterautoscaler/clusterautoscaler.go
  pkg/controller/clusterautoscaler/clusterautoscaler_test.go
Labels: approved, lgtm, size/M

#105 Move management of webhook configurations to operator
  install/03_rbac.yaml
  install/07_servicemonitor.yaml
  install/07_webhooks.yaml
  kustomization.yaml
  pkg/operator/operator.go
  pkg/operator/webhookconfig.go
Labels: approved, lgtm, size/L

#106 Extend cluster-autoscaler cluster role rbac rules with batch/jobs access
  install/03_rbac.yaml
Labels: approved, lgtm, size/XS
