Repository openshift/cluster-autoscaler-operator, pull requests merged in 2019-12, with the labels that each got.

#124 Bug 1779640: Don't suppress errors when reporting operator status
  pkg/operator/status.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#125 bug 1779741: Don't suppress errors when reporting operator status
  pkg/operator/status.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#128 Add resource request to container
  install/07_deployment.yaml
Labels: approved, lgtm, size/XS

#130 Update owners
  OWNERS
Labels: approved, lgtm, size/XS

#126 Bug 1779743: Don't suppress errors when reporting operator status
  pkg/operator/status.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#127 Bug 1779745: Don't suppress errors when reporting operator status
  pkg/operator/status.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S
