Repository openshift/cluster-autoscaler-operator, pull requests merged in 2019-04, with the labels that each got.

#79 Make StatusReporter a Runnable added to the manager
  pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
  pkg/controller/clusterautoscaler/clusterautoscaler_test.go
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, lgtm, size/XXL

#80 Record ClusterAutoscaler events in correct namespace
  pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
  pkg/controller/clusterautoscaler/clusterautoscaler_test.go
  pkg/operator/status_test.go
  test/helpers/helpers.go
Labels: approved, lgtm, size/L

#82 Move from glog to klog
  Gopkg.lock
  Gopkg.toml
  cmd/manager/main.go
  pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
  pkg/controller/machineautoscaler/machineautoscaler_controller.go
  pkg/operator/config.go
  pkg/operator/status.go
  test/e2e/operator_expectations.go
Labels: approved, lgtm, size/L

#84 Always reset LastTransitionTime on Progressing condition
  pkg/controller/clusterautoscaler/clusterautoscaler_test.go
  pkg/operator/status.go
  pkg/operator/status_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  test/helpers/helpers.go
Labels: approved, lgtm, size/L

#88 bump cluster-api-actuator-pkg
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/framework.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/machinehealthcheck/machinehealthcheck.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/machine-api-operator.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/utils.go
  vendor/k8s.io/apiextensions-apiserver/examples/client-go/pkg/apis/cr/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/examples/client-go/pkg/client/clientset/versioned/typed/cr/v1/example.go
  vendor/k8s.io/apiextensions-apiserver/examples/client-go/pkg/client/clientset/versioned/typed/cr/v1/fake/fake_example.go
  vendor/k8s.io/apiextensions-apiserver/examples/client-go/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/apiextensions-apiserver/main.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/fuzzer/fuzzer.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/helpers.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/conversion/converter.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/conversion/nop_converter.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/conversion/webhook_converter.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_discovery_controller.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/helpers.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/validation/validation.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/fake/fake_customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/internalclientset/typed/apiextensions/internalversion/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/internalclientset/typed/apiextensions/internalversion/fake/fake_customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/internalversion/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/apiextensions-apiserver/pkg/cmd/server/options/options.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/establish/establishing_controller.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/aggregator.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/controller.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/status/naming_controller.go
  vendor/k8s.io/apiextensions-apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiextensions-apiserver/pkg/generated/openapi/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/generated/openapi/zz_generated.openapi.go
  vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go
  vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresource/strategy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition/strategy.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/fixtures/resources.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/helpers.go
Labels: approved, lgtm, size/XXL

#85 examples/clusterautoscaler: add commentary on sample values
  examples/clusterautoscaler.yaml
Labels: approved, lgtm, size/XS

#86 Makefile: add -ginkgo.noColor=true for e2e invocations
  Makefile
Labels: approved, lgtm, size/XS

#91 Switch back to master branch of cluster-api-actuator-pkg
  Gopkg.lock
  Gopkg.toml
Labels: approved, lgtm, size/XS

#92 Vendor: update cluster-api-actuator-pkg and simplify
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/openshift/api/apps/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/legacyconfig/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_scheduler.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogapiserver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/webconsole/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/utils.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go
  vendor/github.com/openshift/cluster-version-operator/pkg/cincinnati/cincinnati.go
  vendor/github.com/openshift/cluster-version-operator/pkg/cvo/availableupdates.go
  vendor/github.com/openshift/cluster-version-operator/pkg/cvo/cvo.go
  vendor/github.com/openshift/cluster-version-operator/pkg/cvo/internal/operatorstatus.go
  vendor/github.com/openshift/cluster-version-operator/pkg/cvo/sync_worker.go
  vendor/github.com/openshift/cluster-version-operator/pkg/payload/task.go
  vendor/github.com/openshift/cluster-version-operator/pkg/payload/task_graph.go
  vendor/github.com/openshift/cluster-version-operator/pkg/start/start.go
Labels: approved, lgtm, size/XL

#97 Remove status=Failing support
  pkg/operator/status.go
Labels: approved, lgtm, size/XS
