Repository openshift/cluster-autoscaler-operator, pull requests merged in 2019-11, with the labels that each got.

#119 Secure metrics server
  install/03_rbac.yaml
  install/04_service.yaml
  install/06_servicemonitor.yaml
  install/07_deployment.yaml
  install/09_alertrules.yaml
  install/10_kube_rbac_proxy.yaml
  install/image-references
  pkg/operator/operator.go
Labels: approved, lgtm, size/M

#121 Drop alert temporary
  install/09_alertrules.yaml
Labels: approved, lgtm, size/S

#122 Fix metrics
  install/06_kube_rbac_proxy.yaml
  install/07_deployment.yaml
  install/09_alertrules.yaml
Labels: approved, lgtm, size/S

#123 Add manifest annotations for hosted deployment exclusions
  install/04_service.yaml
  install/06_servicemonitor.yaml
  install/07_deployment.yaml
  install/08_clusteroperator.yaml
Labels: approved, lgtm, size/XS
