Repository openshift/cluster-autoscaler-operator, pull requests merged in 2019-08, with the labels that each got.

#113 Bug 1733471: Fix MachineAutoscaler target updates
  pkg/controller/machineautoscaler/machineautoscaler_controller.go
  pkg/controller/machineautoscaler/machineautoscaler_controller_test.go
  pkg/controller/machineautoscaler/validator_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#114 Bug 1727015: Set Upgradeable condition on ClusterOperator status
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#112 Enable ignore-daemonsets-utilization and skp-nodes-with-local-storage
  README.md
  examples/clusterautoscaler.yaml
  install/01_clusterautoscaler.crd.yaml
  pkg/apis/autoscaling/v1/clusterautoscaler_types.go
  pkg/apis/autoscaling/v1/zz_generated.deepcopy.go
  pkg/controller/clusterautoscaler/clusterautoscaler.go
  pkg/controller/clusterautoscaler/clusterautoscaler_test.go
Labels: approved, lgtm, size/M

#115 Bug 1707065: Add terminationMessagePolicy to the CAO container
  install/07_deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#116 Extend makefile with 'make goimports' target
  Makefile
  hack/goimports.sh
Labels: approved, lgtm, size/S
