Repository openshift/cluster-autoscaler-operator, pull requests merged in 2019-03, with the labels that each got.

#63 Add unit tests for Apply
  pkg/operator/status_test.go
Labels: approved, lgtm, size/M

#65 Add status=progressing for version difference
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, lgtm, size/L

#67 status: Only report available when rollout is complete at new version
  install/00_namespace.yaml
  install/01_clusterautoscaler.crd.yaml
  install/02_machineautoscaler.crd.yaml
  install/03_rbac.yaml
  install/04_deployment.yaml
  install/05_clusteroperator.yaml
  kustomization.yaml
  pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
  pkg/operator/config.go
  pkg/operator/operator.go
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, lgtm, size/L

#69 Operator: move report logic to ApplyStatus function
  pkg/operator/status.go
  pkg/operator/status_test.go
Labels: approved, lgtm, size/L

#62 Don't use an embedded ResourceRange in GPULimits
  Makefile
  install/01_clusterautoscaler.crd.yaml
  pkg/apis/autoscaling/v1alpha1/clusterautoscaler_types.go
  pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/autoscaling/v1alpha1/zz_generated.openapi.go
  pkg/controller/clusterautoscaler/clusterautoscaler_test.go
Labels: approved, size/M

#61 Allow additional arguments to cluster-autoscaler
  Gopkg.lock
  pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
  pkg/operator/config.go
  pkg/operator/operator.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/infra/infra.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/infra/utils.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/machine-api-operator.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/utils.go
  vendor/k8s.io/utils/LICENSE
  vendor/k8s.io/utils/buffer/ring_growing.go
  vendor/k8s.io/utils/clock/clock.go
  vendor/k8s.io/utils/clock/testing/fake_clock.go
  vendor/k8s.io/utils/diff/diff.go
  vendor/k8s.io/utils/exec/doc.go
  vendor/k8s.io/utils/exec/exec.go
  vendor/k8s.io/utils/exec/testing/fake_exec.go
  vendor/k8s.io/utils/field/path.go
  vendor/k8s.io/utils/integer/integer.go
  vendor/k8s.io/utils/io/consistentread.go
  vendor/k8s.io/utils/keymutex/hashed.go
  vendor/k8s.io/utils/keymutex/keymutex.go
  vendor/k8s.io/utils/net/ipnet.go
  vendor/k8s.io/utils/net/net.go
  vendor/k8s.io/utils/nsenter/nsenter.go
  vendor/k8s.io/utils/nsenter/nsenter_unsupported.go
  vendor/k8s.io/utils/path/file.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/semantic/deep_equal.go
  vendor/k8s.io/utils/strings/escape.go
  vendor/k8s.io/utils/strings/line_delimiter.go
  vendor/k8s.io/utils/strings/strings.go
  vendor/k8s.io/utils/temp/dir.go
  vendor/k8s.io/utils/temp/doc.go
  vendor/k8s.io/utils/temp/temptest/dir.go
  vendor/k8s.io/utils/temp/temptest/doc.go
  vendor/k8s.io/utils/temp/temptest/file.go
  vendor/k8s.io/utils/third_party/forked/golang/LICENSE
  vendor/k8s.io/utils/third_party/forked/golang/PATENTS
  vendor/k8s.io/utils/third_party/forked/golang/reflect/deep_equal.go
  vendor/k8s.io/utils/trace/trace.go
Labels: approved, lgtm, size/XXL

#71 ca_controller: implement unit tests
  pkg/controller/clusterautoscaler/clusterautoscaler_test.go
Labels: approved, lgtm, size/L

#72 ca_controller: add Reconcile unit tests
  pkg/controller/clusterautoscaler/clusterautoscaler_test.go
Labels: approved, lgtm, size/M

#75 Fix bug with filtering supported MachineAutoscaler GVKs
  pkg/controller/machineautoscaler/machineautoscaler_controller.go
  pkg/controller/machineautoscaler/machineautoscaler_controller_test.go
  pkg/controller/machineautoscaler/machinetarget.go
  pkg/controller/machineautoscaler/machinetarget_test.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/L

#76 Record events in all controllers
  pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
  pkg/controller/clusterautoscaler/clusterautoscaler_test.go
  pkg/controller/machineautoscaler/machineautoscaler_controller.go
  pkg/controller/machineautoscaler/machineautoscaler_controller_test.go
  pkg/controller/machineautoscaler/machinetarget.go
  pkg/controller/machineautoscaler/machinetarget_test.go
Labels: approved, lgtm, size/L

#77 Add additional logging
  pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
Labels: approved, lgtm, size/XS

#78 verify staleness of vendored cluster-api-actuator-pkg
  Makefile
  hack/verify-actuator-pkg.sh
Labels: approved, lgtm, size/S
