Repository openshift/cluster-autoscaler-operator, pull requests merged in 2019-02, with the labels that each got.

#34 Use the correct ServiceAccount for the operator
  install/0000_50_cluster-autoscaler-operator_03_rbac.yaml
  install/0000_50_cluster-autoscaler-operator_04_deployment.yaml
Labels: approved, lgtm, size/M

#35 Update Cluster autoscaler operator to consume machine.openshift.io
  install/0000_50_cluster-autoscaler-operator_03_rbac.yaml
  pkg/controller/clusterautoscaler/clusterautoscaler.go
  pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
  pkg/controller/clusterautoscaler/clusterautoscaler_test.go
  pkg/controller/machineautoscaler/machineautoscaler_controller.go
  pkg/operator/config.go
  pkg/operator/operator.go
  test/e2e/main.go
Labels: approved, lgtm, size/M

#41 Revert "Disabling ExpectClusterAutoscalerAvailable e2e test temporarily."
  test/e2e/main.go
Labels: approved, lgtm, size/S

#44 Remove unregistered types from supported target types
  pkg/controller/machineautoscaler/machineautoscaler_controller.go
Labels: approved, lgtm, size/M

#37 Allow to configure --scale-down-unneeded-time
  pkg/apis/autoscaling/v1alpha1/clusterautoscaler_types.go
  pkg/controller/clusterautoscaler/clusterautoscaler.go
Labels: approved, lgtm, size/XS

#36 Use kustomize to deploy CA operator in k8s
  install/0000_50_cluster-autoscaler-operator_04_deployment.yaml
  kustomization.yaml
Labels: approved, lgtm, size/S

#43 Change namespace to openshift-machine-api
  README.md
  examples/machineautoscaler.yaml
  install/0000_50_cluster-autoscaler-operator_00_namespace.yaml
  install/0000_50_cluster-autoscaler-operator_03_rbac.yaml
  install/0000_50_cluster-autoscaler-operator_04_deployment.yaml
  pkg/operator/config.go
  test/e2e/main.go
Labels: approved, lgtm, size/M

#47 Prepare test/e2e to be run over pure k8s (over kubemark based machine API)
  Makefile
  cluster-autoscaler-operator-patch.yaml
  kustomization.yaml
  test/e2e/main.go
  test/e2e/operator_expectations.go
  test/resources/cluster.yaml
  test/resources/machine-set.yaml
Labels: approved, lgtm, size/L

#49 Make all scale down arguments optional
  examples/machineautoscaler.yaml
  install/0000_50_cluster-autoscaler-operator_03_rbac.yaml
  pkg/apis/autoscaling/v1alpha1/clusterautoscaler_types.go
  pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/clusterautoscaler/clusterautoscaler.go
  pkg/controller/clusterautoscaler/clusterautoscaler_test.go
  test/e2e/operator_expectations.go
Labels: approved, lgtm, size/L

#50 Add expect for cluster operator status
  pkg/operator/status.go
  test/e2e/main.go
  test/e2e/operator_expectations.go
Labels: approved, lgtm, size/M

#52 Add OpenAPI schema validation
  .gitignore
  Makefile
  install/0000_50_cluster-autoscaler-operator_01_clusterautoscaler.crd.yaml
  install/0000_50_cluster-autoscaler-operator_02_machineautoscaler.crd.yaml
  pkg/apis/autoscaling/v1alpha1/clusterautoscaler_types.go
  pkg/apis/autoscaling/v1alpha1/machineautoscaler_types.go
  pkg/apis/autoscaling/v1alpha1/zz_generated.defaults.go
  pkg/apis/autoscaling/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/L

#53 Add configuration option for autoscaler logging verbosity
  pkg/controller/clusterautoscaler/clusterautoscaler.go
  pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
  pkg/operator/config.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/S

#51 Rename labels from sigs.k8s.io to machine.openshift.io
  test/resources/machine-set.yaml
Labels: approved, lgtm, size/XS

#58 Remove resource limits in operator deployment
  install/0000_50_cluster-autoscaler-operator_04_deployment.yaml
Labels: approved, lgtm, size/XS

#59 Override default CAO image
  cluster-autoscaler-operator-patch.yaml
Labels: approved, lgtm, size/XS

#56 Add tests and change StatusReporter.client to osconfig.Interface
  Gopkg.lock
  pkg/operator/status.go
  pkg/operator/status_test.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/_codegen/main.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/doc.go
  vendor/github.com/stretchr/testify/http/doc.go
  vendor/github.com/stretchr/testify/http/test_response_writer.go
  vendor/github.com/stretchr/testify/http/test_round_tripper.go
  vendor/github.com/stretchr/testify/mock/doc.go
  vendor/github.com/stretchr/testify/mock/mock.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/github.com/stretchr/testify/suite/doc.go
  vendor/github.com/stretchr/testify/suite/interfaces.go
  vendor/github.com/stretchr/testify/suite/suite.go
Labels: approved, lgtm, size/XXL

#57 Add cluster-critical priority to autoscaler-operator
  install/0000_50_cluster-autoscaler-operator_04_deployment.yaml
Labels: approved, lgtm, size/XS

#64 Update list of owners
  OWNERS
Labels: approved, lgtm, size/XS
