Repository openshift/cluster-autoscaler-operator, pull requests merged in 2020-11, with the labels that each got.

#164 Bug 1879162: ensure full boolean arguments
  pkg/controller/clusterautoscaler/clusterautoscaler.go
  pkg/controller/clusterautoscaler/clusterautoscaler_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#181 [OCPCLOUD-809] Add verify-diff check in generate task and enable in CI
  Makefile
  hack/gen-crd.sh
  hack/verify-diff.sh
Labels: approved, lgtm

#179 add current profile annotations to CVO manifests
  install/03_rbac.yaml
Labels: approved, lgtm

#177 add machineset/scale resource to the cluster-autoscaler role
  install/03_rbac.yaml
Labels: approved, lgtm

#185 Bug 1879777: Remove namespace manifest
  install/00_namespace.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#186 [OCPCLOUD-977] Bump scripts to Go 1.15
  Dockerfile
  Makefile
  go.mod
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
  hack/goimports.sh
  vendor/modules.txt
Labels: approved, lgtm
