Repository openshift/cluster-autoscaler-operator, pull requests merged in 2020-04, with the labels that each got.

#147 Bug 1817860: Fix API group on related resources
  pkg/operator/operator.go
  pkg/operator/operator_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#139 BUG 1813069: Drop ClusterAutoscalerNodesNotReady alert
  pkg/controller/clusterautoscaler/monitoring.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#148 Bug 1829263: Bump apiextensions
  hack/gen-crd.sh
  install/01_clusterautoscaler.crd.yaml
  install/02_machineautoscaler.crd.yaml
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#149 Bug 1796412: cluster-reader is unable to view machine resources
  install/10_cluster_reader_rbac.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
