Repository openshift/cluster-autoscaler-operator, pull requests merged in 2020-03, with the labels that each got.

#133 BUG 1806438: Drop run-level
  install/00_namespace.yaml
  install/07_deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#134 Bug 1809325: ROKS - remove additional autoscaler manifests
  hack/gen-crd.sh
  install/01_clusterautoscaler.crd.yaml
  install/02_machineautoscaler.crd.yaml
  install/09_alertrules.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#140 Remove bison from OWNERS file
  OWNERS
Labels: approved, lgtm

#144 Update owners to add new team members
  OWNERS
Labels: approved, lgtm

#142 Set clusterapi flag and env variable for group
  pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
  pkg/operator/config.go
Labels: approved, lgtm
