Repository openshift/cluster-autoscaler-operator, pull requests merged in 2020-09, with the labels that each got.

#161 Bug 1872080: Create Dockerfile.rhel file
  Dockerfile.rhel
  Dockerfile.rhel7
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#162 Bug 1875036: remove Dockerfile.rhel7
  Dockerfile.rhel7
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#163 Bug 1819029: add a document about autoscaler alerts
  docs/user/alerts.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#168 Bug 1883497: Fix missing logs due to mixed klog versions
  cmd/manager/main.go
  go.mod
  pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
  pkg/controller/clusterautoscaler/monitoring.go
  pkg/controller/clusterautoscaler/validator.go
  pkg/controller/machineautoscaler/machineautoscaler_controller.go
  pkg/controller/machineautoscaler/validator.go
  pkg/operator/status.go
  pkg/operator/webhookconfig.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
