Repository openshift/cluster-autoscaler-operator, pull requests merged in 2020-10, with the labels that each got.

#169 Bug 1880320: Bump K8s dependencies to v0.18.9
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#172 add bugzilla component to OWNERS
  OWNERS
Labels: approved, lgtm

#176 add current profile annotations to CVO manifests
  install/00_namespace.yaml
  install/01_clusterautoscaler.crd.yaml
  install/02_machineautoscaler.crd.yaml
  install/03_rbac.yaml
  install/04_service.yaml
  install/05_kube_rbac_proxy.yaml
  install/06_servicemonitor.yaml
  install/07_deployment.yaml
  install/08_clusteroperator.yaml
  install/09_alertrules.yaml
  install/10_cluster_reader_rbac.yaml
Labels: approved, lgtm

#178 Bug 1876469: Update generated CRDs
  hack/gen-crd.sh
  install/01_clusterautoscaler.crd.yaml
  install/02_machineautoscaler.crd.yaml
  pkg/apis/autoscaling/v1beta1/machineautoscaler_types.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
