Repository openshift/cluster-autoscaler-operator, pull requests merged in 2021-04, with the labels that each got.

#196 install/90_alertrules: Drop ClusterAutoscalerOperatorDown
  docs/user/alerts.md
  install/09_alertrules.yaml
Labels: approved, lgtm

#199 Bug 1947785: Move webhook to v1
  pkg/operator/webhookconfig.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#197 Bug 1938467: The default cluster-autoscaler should get default cpu and memory requests if user omits them
  pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#201 Bug 1938467: Fix cluster autoscaler pod requests
  pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#183 Bug 1948706: Add IBM Cloud managed annotations to CVO manifests
  install/03_rbac.yaml
  install/05_kube_rbac_proxy.yaml
  install/10_cluster_reader_rbac.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#198 Add management workload annotations
  install/07_deployment.yaml
  pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
  pkg/util/util.go
Labels: approved, bugzilla/valid-bug, lgtm
