Repository openshift/cluster-autoscaler-operator, pull requests merged in 2021-12, with the labels that each got.

#231 update owners file
  OWNERS
Labels: lgtm, approved

#227 update to Golang1.17
  .ci-operator.yaml
  Dockerfile
  Dockerfile.rhel
  Makefile
  go.mod
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
  hack/goimports.sh
  pkg/apis/autoscaling/v1/zz_generated.deepcopy.go
  pkg/apis/autoscaling/v1beta1/zz_generated.deepcopy.go
  tools.go
  vendor/github.com/cespare/xxhash/v2/go.mod
  vendor/github.com/cespare/xxhash/v2/go.sum
  vendor/github.com/fatih/color/go.mod
  vendor/github.com/fatih/color/go.sum
  vendor/github.com/fsnotify/fsnotify/go.mod
  vendor/github.com/fsnotify/fsnotify/go.sum
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/gobuffalo/flect/go.mod
  vendor/github.com/gobuffalo/flect/go.sum
  vendor/github.com/google/gofuzz/go.mod
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/imdario/mergo/go.mod
  vendor/github.com/imdario/mergo/go.sum
  vendor/github.com/json-iterator/go/go.mod
  vendor/github.com/json-iterator/go/go.sum
  vendor/github.com/mattn/go-colorable/go.mod
  vendor/github.com/mattn/go-colorable/go.sum
  vendor/github.com/mattn/go-isatty/go.mod
  vendor/github.com/mattn/go-isatty/go.sum
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/go.mod
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/go.sum
  vendor/github.com/prometheus/procfs/go.mod
  vendor/github.com/prometheus/procfs/go.sum
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/pflag/go.mod
  vendor/github.com/spf13/pflag/go.sum
  vendor/golang.org/x/oauth2/go.mod
  vendor/golang.org/x/oauth2/go.sum
  vendor/golang.org/x/term/go.mod
  vendor/golang.org/x/term/go.sum
  vendor/golang.org/x/xerrors/go.mod
  vendor/gomodules.xyz/jsonpatch/v2/go.mod
  vendor/gomodules.xyz/jsonpatch/v2/go.sum
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
Labels: lgtm, approved

#234 Update makefile to support podman
  Makefile
  README.md
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-mod.sh
  hack/go-vet.sh
  hack/goimports.sh
  hack/imagebuilder.sh
  hack/owner_reset.sh
Labels: lgtm, approved

#233 Bug 2026178: update alerts to match style guidance
  pkg/controller/clusterautoscaler/monitoring.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low, qe-approved

#236 Bug 2034484: fix: missed rbac and latest library-go
  go.mod
  go.sum
  install/03_rbac.yaml
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
